### ISSUE TITLE
element-ui vs iview?

### ISSUE THREAD

**Issue by zhaojh329** [zhaojh329/vuci#1]
element-ui vs iview?

**Comment by zhaojh329** [comment]
I have switched to iView.

**Comment by zhaojh329** [comment]
feeling.

**Comment by imudin** [comment]
@zhaojh329 haha I see. The same here my feeling is taking me to iView too. But I am doing company's project. If it is not stable enough, It is all on me. So having hard time to choose one of them. Personally I love iView, so pretty.  but element-ui has more stars, and it has good example vue-element-admin.

**Comment by imudin** [comment]
What about IE support?

**Comment by zhaojh329** [comment]
Iview has also been used by many well-known companies.

**Comment by zhaojh329** [comment]
https://www.iviewui.com/docs/guide/introduce-en#Who's_using_iView

**Comment by imudin** [comment]
I see! thank you

**Comment by gustawdaniel** [comment]
In my opinion eleme.io has problem with screen scaling. Especially lacking support for mobile devices is distressing:

> https://github.com/ElemeFE/element/issues/3656

Although community asked about support for mobile in last comments in issue:

> https://github.com/ElemeFE/element/issues/7237

it was ignored.

I switched from eleme.io to iview today.
