### ISSUE TITLE
我先支持下

### ISSUE THREAD

**Issue by fuqiang03** [zhaojh329/vuci#2]
我先支持下，正在编译中
![image](https://user-images.githubusercontent.com/26851715/34903275-4f713348-f869-11e7-90e8-7fe63a90f4b9.png)

**Comment by daofeng2015** [comment]
请全局翻再make V=s

**Comment by fuqiang03** [comment]
![image](https://user-images.githubusercontent.com/26851715/34919095-55c05a04-f999-11e7-85c8-ee971b466009.png)
确实缺少这个文件

**Comment by zhaojh329** [comment]
master（17.0及以后版本）版本是STAGING_DIR_HOSTPKG
cc及以前版本是STAGING_DIR_HOST
我后面会修复这个问题。

**Comment by zhaojh329** [comment]
已修复
