### ISSUE TITLE
NPM package-lock.json warning 

### ISSUE THREAD

**Issue by arky** [zhaojh329/vuci#5]
When you try to do 'npm install' you will give following warning. Using yarn as a work-around for now.

> $ npm install
> npm WARN saveError ENOENT: no such file or directory, open '/home/vuci/package.json'
> npm notice created a lockfile as package-lock.json. You should commit this file.
> npm WARN enoent ENOENT: no such file or directory, open '/home/vuci/package.json'
> npm WARN vuci No description
> npm WARN vuci No repository field.
> npm WARN vuci No README data
> npm WARN vuci No license field.
> 
> up to date in 1.353s
> found 0 vulnerabilities
>

**Comment by zhaojh329** [comment]
I have already edited it.
https://github.com/zhaojh329/vuci#how-to-use
